language: php

sudo: false

php:
  - 7.0

before_script:
  - phpenv rehash

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

before_install:
  - pip install --user codecov

after_success:
  - codecov

notifications:
  email: false
